### ISSUE TITLE
dxf open problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Heeks/heekscad#363]
```
Hello,
Heekscad not open attached dxf.
I exported from corel11 other cad program open correct.
Regards.
```

Original issue reported on code.google.com by `bigla...@startolj.hu` on 31 Aug 2011 at 5:29

Attachments:
* [ACCEL1C11.dxf](https://storage.googleapis.com/google-code-attachments/heekscad/issue-363/comment-0/ACCEL1C11.dxf)

**Comment by neomilium** [comment]
Obsolete
