### ISSUE TITLE
OS X Build and missing toolbar icons [Solved]

### ISSUE THREAD

**Issue by Blokkendoos** [Heeks/heekscad#408]
Successfully built HeeksCAD and CNC on OS X. Though the GUI shows an incomplete toolbars ~~and missing options' tree~~. 
Only the dropdown (CFlyout*) items are missing in the toolbars. The BitmapButtons are ok.
Debugging (with GDB) wxWidgets is harder than I expected (I am not a developer).
Attached files show the GUI as well as the wxWidgets alert which accompanies Quitting the App.

Has someone more knowledgeable, of wxWidgets on Mac in particular, a hint for me on how to fix this?
Thanks in advance,
Jo

**Details**
OS X 10.8.5
Macports portfiles:
cmake @3.5.0_0 
OpenCascade CE, macport oce@0.17_0
wxWidgets-3.0 @3.0.2_4 
boost @1.59.0_2+no_single+no_static+python27+universal
Sources used:
opencamlib: https://github.com/aewallin/opencamlib
libarea:  https://github.com/Heeks/libarea.git
heekscad: https://github.com/Heeks/heekscad.git
heekscnc: https://github.com/Heeks/heekscnc.git

![2016-03-26 om 23 31 58 heekscad gui os x 10 8 5](https://cloud.githubusercontent.com/assets/633633/14062868/111bee14-f3af-11e5-8a6b-c5f4711b4301.png)
![2016-03-26 om 23 32 15 wxwidgets alert](https://cloud.githubusercontent.com/assets/633633/14062869/111d1f46-f3af-11e5-8e42-77bfe6a3843d.png)
![2016-03-26 om 23 33 23 heekscad dxf import](https://cloud.githubusercontent.com/assets/633633/14062870/111d4f16-f3af-11e5-9c5c-95ff8a49a275.png)

**Comment by Blokkendoos** [comment]
The missing options tree was caused by my workaround for a missing or invalid font (setting wxPG_PIXELS_PER_UNIT to 16). Fixed this in propgrid.cpp:2693:

```
    if ( m_font.Ok() )
        // This should be otherwise called by SetOwnFont
        CalculateFontAndBitmapStuff( wxPG_DEFAULT_VSPACING );
    else if ( wxNORMAL_FONT->Ok() )
    {
        m_font = *wxNORMAL_FONT;
        CalculateFontAndBitmapStuff( wxPG_DEFAULT_VSPACING );
    }
    else
    {
        wxFont useFont = wxScrolledWindow::GetFont();
        wxScrolledWindow::SetOwnFont( useFont );
    }
```

The missing / misplaced toolbar buttons still remain.
![schermafbeelding 2016-04-01 om 22 02 11](https://cloud.githubusercontent.com/assets/633633/14218809/d2ca3ea2-f856-11e5-94a8-905e2f581e31.png)

**Comment by Blokkendoos** [comment]
The controls not showing seems to be [wxWidget idiosyncratic behaviour on OS X](https://forums.wxwidgets.org/viewtopic.php?t=40283). Creating the toolbars as a child of a wxPanel worked! Changed the issue description to [Solved]
![schermafbeelding 2016-04-09 om 00 08 00](https://cloud.githubusercontent.com/assets/633633/14398899/0da80ea0-fde8-11e5-958a-a79621399a7c.png)

**Comment by ffurano** [comment]
Hi,

 Brilliant, I was just having the same issues as you. I recently cloned, though, and I don't see your fixes. Didn't you do a pull request ?

 Moreover, the fix for the propgrid.cpp:2693 in the source I have was at line 3693

 Being completely ignorant on wxWidgets, what do you mean with "Creating the toolbars as a child of a wxPanel worked" ? I see that the toolbars are created in HeeksFrame.cpp, what did you do there ?

Thank you!
f
