### ISSUE TITLE
Clearance height value is treated as an integer in pocket operations (HeeksCNC)

### ISSUE THREAD

**Issue by lpgasparotto** [Heeks/heekscad#413]
If I set 15 as the clearance height value I get this line of code:
N60G00Z15S6500M03
It should be:
N60G00Z15.0S6500M03
or
N60G00Z15.S6500M03

There are controllers which consider integer numbers as steps in the lowest resolution available (i.e. 0.0015).

Also, if I change that value for 15.0 nothing changes and I get the same line:
N60G00Z15S6500M03

Maybe this is related to Opencam lib.

**Comment by neomilium** [comment]
Please use appropriated issue tracker : HeeksCNC
